const items = [
  {
    title: "บรอกโคลี",
    description: "จากฟาร์มออร์แกนิกเชียงใหม่ ปลูกบนดอยสูง ปลอดสารพิษ",
    pcs: 87,
    price: 45,
    unit: "บาท/กก.",
    category: "ผัก",
  },
  {
    title: "แครอท",
    description: "แหล่งปลูกจังหวัดสระบุรี ดินร่วนปนทราย ให้รสหวานกรอบ",
    pcs: 92,
    price: 30,
    unit: "บาท/กก.",
    category: "ผัก",
  },
  {
    title: "ผักโขม",
    description: "เก็บสดทุกวันจากฟาร์ม hydroponic กรุงเทพมหานคร",
    pcs: 78,
    price: 40,
    unit: "บาท/กก.",
    category: "ผัก",
  },
  {
    title: "คะน้า",
    description: "จากเกษตรกรจังหวัดนครปฐม ปลูกแบบอินทรีย์",
    pcs: 85,
    price: 35,
    unit: "บาท/กก.",
    category: "ผัก",
  },
  {
    title: "ฟักทอง",
    description: "พันธุ์ญี่ปุ่น ปลูกที่จังหวัดลพบุรี เนื้อแน่นรสหวาน",
    pcs: 63,
    price: 55,
    unit: "บาท/กก.",
    category: "ผัก",
  },
  {
    title: "มะเขือเทศ",
    description: "พันธุ์เชอร์รี่ ปลูกที่จังหวัดกาญจนบุรี ปลอดสารเคมี",
    pcs: 95,
    price: 60,
    unit: "บาท/กก.",
    category: "ผัก",
  },
  {
    title: "พริกหวาน",
    description: "นำเข้าจากเกาหลี ปลูกในระบบ Greenhouse จังหวัดระยอง",
    pcs: 71,
    price: 120,
    unit: "บาท/กก.",
    category: "ผัก",
  },
  {
    title: "หัวหอมใหญ่",
    description: "จากโครงการหลวงเชียงใหม่ ปลูกในที่สูงอากาศเย็น",
    pcs: 88,
    price: 25,
    unit: "บาท/กก.",
    category: "ผัก",
  },
  {
    title: "กระเทียม",
    description: "พันธุ์ดีจากจังหวัดศรีสะเกษ กลิ่นฉุนเฉพาะตัว",
    pcs: 96,
    price: 50,
    unit: "บาท/กก.",
    category: "ผัก",
  },
  {
    title: "กะหล่ำปลี",
    description: "จากฟาร์มจังหวัดเพชรบูรณ์ ปลูกในสภาพอากาศเย็น",
    pcs: 82,
    price: 30,
    unit: "บาท/กก.",
    category: "ผัก",
  },
  {
    title: "ผักกาดหอม",
    description: "จากฟาร์м hydroponic ปทุมธานี สดสะอาดทุกวัน",
    pcs: 79,
    price: 40,
    unit: "บาท/กก.",
    category: "ผัก",
  },
  {
    title: "แตงกวา",
    description: "พันธุ์พื้นเมือง ปลูกที่จังหวัดนครศรีธรรมราช",
    pcs: 91,
    price: 20,
    unit: "บาท/กก.",
    category: "ผัก",
  },
  {
    title: "ข้าวโพดอ่อน",
    description: "จากจังหวัดสกลนคร เก็บเกี่ยวขณะยังอ่อนอยู่",
    pcs: 84,
    price: 35,
    unit: "บาท/กก.",
    category: "ผัก",
  },
  {
    title: "หน่อไม้ฝรั่ง",
    description: "ปลูกที่จังหวัดราชบุรี ในระบบการผลิตมาตรฐาน GAP",
    pcs: 67,
    price: 85,
    unit: "บาท/กก.",
    category: "ผัก",
  },
  {
    title: "เห็ดหอม",
    description: "จากฟาร์มเพาะเห็ดจังหวัดสุโขทัย ใช้ขี้เลื่อยไม้ยางพารa",
    pcs: 73,
    price: 90,
    unit: "บาท/กก.",
    category: "ผัก",
  },
  {
    title: "อกไก่",
    description: "จากไก่พันธุ์เนื้อออร์แกนิก ฟาร์มจังหวัดฉะเชิงเทรา",
    pcs: 58,
    price: 150,
    unit: "บาท/กก.",
    category: "เนื้อไก่",
  },
  {
    title: "สะโพкไก่",
    description: "ไก่พื้นเมืองไทย เลี้ยงแบบปล่อยอิสระ จังหวัดสระแก้ว",
    pcs: 62,
    price: 110,
    unit: "บาท/กก.",
    category: "เนื้อไก่",
  },
  {
    title: "สันในไก่",
    description: "จากไก่พันธุ์ Cobb ฟาร์มมาตรฐานจังหวัดปทุมธานี",
    pcs: 69,
    price: 130,
    unit: "บาท/กก.",
    category: "เนื้อไก่",
  },
  {
    title: "เนื้อวัวส่วนสันนอก",
    description: "เนื้อวัว Wagyu เลี้ยงที่จังหวัดบุรีรัมย์",
    pcs: 45,
    price: 899,
    unit: "บาท/กก.",
    category: "เนื้อวัว",
  },
  {
    title: "เนื้อวัวส่วนสันใน",
    description: "เนื้อ Angus จากฟาร์มจังหวัดนครราชสีมา",
    pcs: 38,
    price: 950,
    unit: "บาท/กก.",
    category: "เนื้อวัว",
  },
  {
    title: "เนื้อวัวบด",
    description: "เนื้อส่วนShoulder จากวัวพันธุ์พื้นเมืองจังหวัดอุบลราชธานี",
    pcs: 52,
    price: 299,
    unit: "บาท/กก.",
    category: "เนื้อวัว",
  },
  {
    title: "สันคอหมู",
    description: "จากสุกรพันธุ์ดูร็อค ฟาร์มมาตรฐานจังหวัดชลบุรี",
    pcs: 65,
    price: 180,
    unit: "บาท/กก.",
    category: "เนื้อหมู",
  },
  {
    title: "สันนอกหมู",
    description: "สุกรพันธุ์แลนด์เรซ ฟาร์มจังหวัดพระนครศรีอยุธยา",
    pcs: 59,
    price: 220,
    unit: "บาท/กก.",
    category: "เนื้อหมู",
  },
  {
    title: "ซี่โครงหมู",
    description: "จากสุกรขุน ฟาร์มอินทรีย์จังหวัดนครปฐม",
    pcs: 48,
    price: 250,
    unit: "บาท/กก.",
    category: "เนื้อหมู",
  },
  {
    title: "สามชั้น",
    description: "ส่วน belly จากสุกรพันธุ์เบลเยี่ยม ฟาร์มจังหวัดสระบุรี",
    pcs: 56,
    price: 190,
    unit: "บาท/กก.",
    category: "เนื้อหมู",
  },
  {
    title: "เนื้อ salmon",
    description: "แซลมอนนอร์เวย์ นำเข้าโดยตรง แช่แข็งอย่างดี",
    pcs: 42,
    price: 690,
    unit: "บาท/กก.",
    category: "อาหารทะเล",
  },
  {
    title: "เนื้อ shrimp",
    description: "กุ้งขาวแวนนาไม จากฟาร์มจังหวัดสมุทรสาคร",
    pcs: 76,
    price: 450,
    unit: "บาท/กก.",
    category: "อาหารทะเล",
  },
  {
    title: "ปลากระพง",
    description: "จากฟาร์มเลี้ยงระบบปิดจังหวัดชลบุรี เนื้อแน่นสด",
    pcs: 61,
    price: 320,
    unit: "บาท/กก.",
    category: "อาหารทะเล",
  },
  {
    title: "ปลาดอลลี่",
    description: "นำเข้าจากเวียดนาม แช่แข็งเร็วที่แหล่งผลิต",
    pcs: 54,
    price: 280,
    unit: "บาท/กก.",
    category: "อาหารทะเล",
  },
  {
    title: "หอยเชลล์",
    description: "จากทะเลอันดามัน จังหวัดพังงา เก็บเกี่ยววันต่อวัน",
    pcs: 99,
    price: 799,
    unit: "บาท/กก.",
    category: "อาหารทะเล",
  },
];
export default items;