-- AlterTable
ALTER TABLE `table` ADD COLUMN `floorPlanLocked` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `height` DOUBLE NOT NULL DEFAULT 120,
    ADD COLUMN `posX` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `posY` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `rotation` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `seatCount` INTEGER NOT NULL DEFAULT 4,
    ADD COLUMN `shape` VARCHAR(191) NOT NULL DEFAULT 'circle',
    ADD COLUMN `width` DOUBLE NOT NULL DEFAULT 120;
